required = [
  "github.com/avinoamr/godocdown",
]

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/rollbar/rollbar-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/grpc-ecosystem/go-grpc-middleware"
  version = "1.0.0"
